//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT4_DamThuyHuong_2210900028_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banner
    {
        public int maBanner { get; set; }
        public string hinhAnh { get; set; }
        public Nullable<bool> trangThai { get; set; }
    }
}
