//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamThuyHuong_K22CNT4_2210900028_project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donHang()
        {
            this.chiTietDonHangs = new HashSet<chiTietDonHang>();
        }
    
        public int maDonHang { get; set; }
        public Nullable<int> maKhachHang { get; set; }
        public string tenKhachHang { get; set; }
        public decimal tongTien { get; set; }
        public string diaChiGiaoHang { get; set; }
        public string dienthoai { get; set; }
        public Nullable<decimal> phiVanChuyen { get; set; }
        public Nullable<int> phuongThucThanhToan { get; set; }
        public Nullable<int> trangThai { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiTietDonHang> chiTietDonHangs { get; set; }
        public virtual khachHang khachHang { get; set; }
    }
}
