//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamThuyHuong_K22CNT4_2210900028_project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quanTri
    {
        public int maQuanTri { get; set; }
        public string tenQuanTri { get; set; }
        public string email { get; set; }
        public string matKhau { get; set; }
        public string diaChi { get; set; }
        public Nullable<bool> trangThai { get; set; }
    }
}
