//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamThuyHuong_K22CNT4_2210900028_project2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanPham()
        {
            this.chiTietDonHangs = new HashSet<chiTietDonHang>();
            this.danhGias = new HashSet<danhGia>();
        }
        [Display(Name = "Mã")]
        public int maSanPham { get; set; }
        [Display(Name = "Tên sản phẩm")]
        [Required(ErrorMessage = "**")]
        public string tenSanPham { get; set; }
        [Display(Name = "Mô tả")]
        public string moTa { get; set; }
        [Display(Name = "Đơn giá")]
        public decimal gia { get; set; }
        [Display(Name = "Hình ảnh")]
        public string hinhAnh { get; set; }
        [Display(Name = "Màu sắc")]
        public string mauSac { get; set; }
        [Display(Name = "Số lượng")]
        public int soLuong { get; set; }
        [Display(Name = "Danh mục")]
        public Nullable<int> maDanhMuc { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> trangThai { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiTietDonHang> chiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<danhGia> danhGias { get; set; }
        public virtual danhMuc danhMuc { get; set; }
    }
}
